emreakay/CodeIgniter-Aauth

- README.md
- sql/Aauth_v2.sql
Minor edit to fix password size issue in the database as requested by @marcoscassiano
> Password storage size bug fix

- application/config/aauth.php
- application/language/english/aauth_lang.php
- application/libraries/Aauth.php
- added configurable login over name or email
- cleaned the config file (a lil prestep for a better documentation)
- added db profile (would close #34)
- removed 2 unused functions (user_exsist_by_name, user_exsist_by_id)
- fixed cookie creation for reCAPTCHA if it's not active
- changed the copyright info to this year
- configurable login over name or email by suggestion from @tswagger 
- added create_group and update_group $definiton from @tswagger SQL changes
- changed list_user_var_keys's output from array to object (similar to list_system_var_keys)
- fixed set_system_var bug (issue #39)
- added config var for reset_password_link and verification_link
- added checks from create_user in update_user 
- user_exsist_by_email, valid_email
- min-max pass length
- user_exsist_by_name, …
> some fixes and db_profile added

- application/libraries/Aauth.php
* #47 Typos in function names. (user_exist functions)
* #46 Variable scope error. (within the update_user() function)
*  remind_password() now returns true and false. (true if email sent) (false if the email address doesn't exist in the DB).
> I highly recommend merging this branch in order to retain elegance and symmetry within the Aauth library.
> Urgent fixes for #47, #46 and Improvements

- README.md
- application/config/aauth.php
- application/helpers/googleauthenticator_helper.php
- application/language/english/aauth_lang.php
- application/libraries/Aauth.php
- sql/Aauth_v2.sql
added Time-Based One-Time Password
- ``totp_active`` added to config vars
- ``totp_only_on_ip_change`` added to config vars
- ``totp_reset_over_reset_password`` added to config vars
added configuration to not use cookies if sessions are enabled.
- ``use_cookies`` added to config vars
changed some default config vars to increase the security
- ``no_permission`` to FALSE
- ``max`` to 24
- ``valid_chars`` to empty array
> TOTP and some improvements

- application/libraries/Aauth.php
- sql/Aauth_v2.sql
@ManeBit done :smile: 
added #49 in my PR too with @tswagger's idea :+1:
> fix for #51 'is_allowed() bug'

- application/libraries/Aauth.php
This will fix issue #59 the way that I proposed in the issue.
> Fix issue with messages

- application/libraries/Aauth.php
- sql/Aauth_v2.sql
problem while using session driver as "database" and "use_cookies" true in aauth config
> fix for #66

- application/language/spanish/aauth_lang.php
> Spanish Language Added

- application/config/aauth.php
changed use_cookies to true to provide CI2 Support
> Updated aauth.php

- application/libraries/Aauth.php
changing lang key from 'aauth_error_login_failed' to 'aauth_error_no_user' as the lang key 'aauth_error_login_failed' doesn't exist.
> 'aauth_error_login_failed' key doesn't exist

- application/language/french/aauth_lang.php
Hi, i'm CTO in a french Web Agency.
My team just starting to use Aauth library and we want to support you.
This is the first part of our contribution. I hope some other will follow.
This is the french language file.
FIY: I replaced some simple quotes for double quotes caused by the specifications of our language.
> Add first version of french language file

- application/config/aauth.php
Update the config file for readability with comments on top page.
Commenting with the same approach of CodeIgniter configurations files.
Profiling with the same approach of CodeIgniter database configuration file (multidimensional arrays).
Add some comment from doc, wiki and github page.
Move 'Verification' variable before 'verification link' for more comprehension.
> Update config file for readability and comprehension

- application/libraries/Aauth.php
"valid" variable was declared and assigned two time
> Double declaration and assignation of valid flag

- .gitignore
- application/config/aauth.php
- application/libraries/Aauth.php
Add config variable for setting hash algorithm
> Custom hash method

- application/helpers/recaptchalib_helper.php
Someone committed a print_r in the recapcha helper that will occur if the capcha is successfully validated.
> Removed print_r in recapcha helper

- application/language/english/aauth_lang.php
- application/libraries/Aauth.php
added in allow_user & allow_group check if perm exists
added in allow_group check if group exists
changed 'TOTP Code' to 'Authentication Code' in english lang file
> added perm/group exists checks in allow_user & allow_group (fix for #90 allow_user and allow_group problem)

- application/libraries/Aauth.php
Hi 
I just made couple of changes as sugested. In an ealier resuest.
> Minor fixes to optional prama fix  

- application/language/indonesian/aauth_lang.php
Hi @emreakay  - do you mind to take a look for this new translation for indonesian language?
> add indonesian  language file translation

- application/helpers/recaptchalib_helper.php
- application/libraries/Aauth.php
ReCAPTCHA PHP7 fix (fix for #107)
added a check if user has email or name already (fix for #109)
> lil enhancements

- index.html
- added headlines in the Quick Start section
- changed typo from the last sentence (me to us, in the sentence before u wrote from `we are ...`)
- fixed `Quick Start`-Section (changed `deny` to `deny_group`) (found by #118)
@emreakay the page looks nice, here some headers :smile: and a bit typo. Can you add a link to the project description?
Preview available at [rejack.github.io/CodeIgniter-Aauth/](http://rejack.github.io/CodeIgniter-Aauth/)
> lil page changes

- application/language/simplified-chinese/aauth_lang.php
- application/language/traditional-chinese/aauth_lang.php
Traditional Chinese is used by Taiwan, Hong Kong 
Simplified Chinese is used by China, Singapore and Malaysia
> Add language support for Chinese

- application/libraries/Aauth.php
https://github.com/emreakay/CodeIgniter-Aauth/issues/162
> Fix for count_unread_pms

- application/language/spanish/aauth_lang.php
Small correction in the translation
> Correction of phrase

- application/language/swedish/aauth_lang.php
> Swedish translation

- application/language/turkish/aauth_lang.php
I have Bulgarian translation and want to commit it.
> BG translation

- application/config/aauth.php
- application/libraries/Aauth.php
Hi, I've changed some PHP keywords to comply with [this standard](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) in PSR2. It's admittedly a small fix but I hope it helps!
> Change PHP keywords to comply with PSR2

- application/language/indonesian/aauth_lang.php
fixed typo and added indonesian error message for `reset_password()` if ver_code empty/invalid
> fixed typo and added error message translation
